### ISSUE TITLE
Establish one source of truth for the version so that the versions never get out of sync

### ISSUE THREAD

**Issue by onunezrsd** [miracle-wm-org/miracle-wm#197]
Upon installing through snap, wrong version is installed or reported

sudo snap search miracle-wm
Name        Version  Publisher        Notes    Summary
miracle-wm  0.3.0    matthew-kosarek  classic  miracle-wm is a Wayland compositor based on mir

Once installed it reports wrong verison

miracle-wm -V
[2024-07-31 17:43:56.906707] <information> miracle-main: Welcome to miracle-wm v0.2.1

**Comment by mattkae** [comment]
Oops! That's my bad. Thanks for finding this.

A good solution to future-proof that version going forward would be to define the version in one place (Cmake probably)

**Comment by mattkae** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [One source of truth for the version](https://trello.com/c/XJ5b4bMb/4-one-source-of-truth-for-the-version)

**Comment by mattkae** [comment]
## Tasks (separate pull requests)
- [ ] Define the version in Cmake only
- [ ] Load the version in `version.h` in miracle-wm
- [ ] Propagate the version to the snap (relies on #59)
